FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

RUN mkdir -p app/
RUN mkdir -p app/frontend

WORKDIR /frontend

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
COPY yarn.lock ./

# install project dependencies
RUN yarn install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN yarn build

EXPOSE 8080

CMD ["http-server", "-P", "http://localhost:8080?", "dist"]